spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-34-233-157-189.compute-1.amazonaws.com:5432/dahbh1juv4p8q8?user=zofbdzgxwrvkle&password=d45a179ebd7ce654aaca8ba77e401296d91ea4085a7fbe3e9b28cec1882805c8
    driver-class-name: org.postgresql.Driver
    username:
    password:
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5

logging:
  level:
    root: INFO
    org.springframework: INFO